const Actions = {
  GET_ADVERTS: "GET_ADVERTS",
  SET_ADVERTS: "SET_ADVERTS",
  SET_IS_EXCHANGE_ADVERTS: "SET_IS_EXCHANGE_ADVERTS",
  SET_NUMBER_VALUE_BY_FIELD: "SET_INPUT_VALUE_BY_FIELD",
  SET_MODEL: "SET_MODEL",
  SET_CARCASES: "SET_CARCASES",
  SET_FUELS: "SET_FUELS",
  SET_TRANSMISSIONS: "SET_TRANSMISSIONS",
  SET_GEARINGS: "SET_GEARINGS",
  SET_COLORS: "SET_COLORS",
  SET_CURRENCY: "SET_CURRENCY",
  CLOSE_TAG: "CLOSE_TAG",
  ADD_MODEL_AUTO: "ADD_MODEL_AUTO",
  REMOVE_MODEL_AUTO: "REMOVE_MODEL_AUTO",
  RESET_FILTER: "RESET_FILTER",
  GET_MORE_ADVERTS: "GET_MORE_ADVERTS",
  SET_MORE_ADVERTS: "SET_MORE_ADVERTS",
  SET_ORDER_ADVERTS: "SET_ORDER_ADVERTS",
  GO_SEARCH: "GO_SEARCH",
};

export default Actions;
