const Actions = {
  SET_ALL_MODELS: "SET_ALL_MODELS",
  GET_ALL_SERIES_OF_MODEL: "GET_ALL_SERIES_OF_MODEL",
  SET_ALL_SERIES_OF_MODEL: "SET_ALL_SERIES_OF_MODEL",
  GET_ALL_GENERATION_OF_SERIES: "GET_ALL_GENERATION_OF_SERIES",
  SET_ALL_GENERATION_OF_SERIES: "SET_ALL_GENERATION_OF_SERIES",
  SET_ALL_COLOR_NAMES: "SET_ALL_COLOR_NAMES",
  SET_ALL_CARCASE_NAMES: "SET_ALL_CARCASE_NAMES",
  SET_ALL_FUEL_NAMES: "SET_ALL_FUEL_NAMES",
  GET_ALL_OPTION_CAR_NAMES: "GET_ALL_OPTION_CAR_NAMES",
};

export default Actions;
