const Actions = {
  SET_IS_LOADING: "SEARCH/SET_IS_LOADING",
  SET_SEARCH_STR: "SEARCH/SET_SEARCH_STR",
  SET_SEARCH_BY: "SEARCH/SET_SEARCH_BY",
  SET_SEARCH_INFO_TO_RESULT: "SEARCH/SET_SEARCH_INFO_TO_RESULT",
  RESET_SEARCH_DATA: "SEARCH/RESET_SEARCH_DATA",
  SEARCH_ADVERTS: "SEARCH/SEARCH_ADVERTS",
  SEARCH_ADVERTS_MORE: "SEARCH/SEARCH_ADVERTS_MORE",
  SET_SEARCH_ADVERTS_MORE: "SEARCH/SET_SEARCH_ADVERTS_MORE",
  SET_ADVERTS: "SEARCH/SET_ADVERTS",
  SET_ADVERTS_BY_KEY: "SEARCH/SET_ADVERTS_BY_KEY",
  SEARCH_ADVERTS_BY_NAME: "SEARCH/SEARCH_ADVERTS_BY_NAME",
  SEARCH_ADVERTS_BY_RUBLES: "SEARCH/SEARCH_ADVERTS_BY_RUBLES",
  SEARCH_ADVERTS_BY_DOLLARS: "SEARCH/SEARCH_ADVERTS_BY_DOLLARS",
  SEARCH_ADVERTS_BY_MILEAGE: "SEARCH/SEARCH_ADVERTS_BY_MILEAGE",
  SEARCH_ADVERTS_BY_CITY: "SEARCH/SEARCH_ADVERTS_BY_CITY",
  SEARCH_ADVERTS_BY_OTHER: "SEARCH/SEARCH_ADVERTS_BY_OTHER",
};

export default Actions;
