const Actions = {
  SET_IS_LOADING: "SEARCH/SET_IS_LOADING",
  CLEAR_SEARCH_DATA: "SEARCH/CLEAR_SEARCH_DATA",
  SEARCH_ADVERTS_BY_NAME: "SEARCH/SEARCH_ADVERTS_BY_NAME",
  SET_ADVERTS_BY_NAME: "SEARCH/SET_ADVERTS_BY_NAME",
  SEARCH_ADVERTS_BY_RUBLES: "SEARCH/SEARCH_ADVERTS_BY_RUBLES",
  SET_ADVERTS_BY_RUBLES: "SEARCH/SET_ADVERTS_BY_RUBLES",
  SEARCH_ADVERTS_BY_DOLLARS: "SEARCH/SEARCH_ADVERTS_BY_DOLLARS",
  SET_ADVERTS_BY_DOLLARS: "SEARCH/SET_ADVERTS_BY_DOLLARS",
  SEARCH_ADVERTS_BY_MILEAGE: "SEARCH/SEARCH_ADVERTS_BY_MILEAGE",
  SET_ADVERTS_BY_MILEAGE: "SEARCH/SET_ADVERTS_BY_MILEAGE",
  SEARCH_ADVERTS_BY_CITY: "SEARCH/SEARCH_ADVERTS_BY_CITY",
  SET_ADVERTS_BY_CITY: "SEARCH/SET_ADVERTS_BY_CITY",
  SEARCH_ADVERTS_BY_OTHER: "SEARCH/SEARCH_ADVERTS_BY_OTHER",
  SET_ADVERTS_BY_OTHER: "SEARCH/SET_ADVERTS_BY_OTHER",
};

export default Actions;
