const Actions = {
  CHECK_IS_LOGINED: "USER/CHECK_IS_LOGINED",
  SET_USER: "USER/SET_USER",
  TRY_LOGOUT: "USER/TRY_LOGOUT",
  TRY_LOGIN: "USER/TRY_LOGIN",
  TRY_SIGNIN: "USER/TRY_SIGNIN",
  LOGOUT: "USER/LOGOUT",
  SAVE_FILTER_OPTIONS: "USER/SAVE_FILTER_OPTIONS",
  SET_FILTERS: "USER/SET_FILTERS",
  GET_FILTERS: "USER/GET_FILTERS",
  UPDATE_FILTER: "USER/UPDATE_FILTER",
  REMOVE_FILTER: "USER/REMOVE_FILTER",
};

export default Actions;
